export interface ExtractedQuery {
  original_prompt: string;
  actual_search_queries: string[];
  tool_use_timestamp: string;
}

export interface AnalysisResult {
  id: string;
  keyword: string;
  extracted_queries: string[];
  h2_strategy: string; // Generated by Gemini
  created_at: string;
}

export interface LogEntry {
  timestamp: string;
  type: 'error' | 'success' | 'warning' | 'info';
  message: string;
}

export enum AppState {
  CHECKING_SERVER = 'CHECKING_SERVER',
  SERVER_OFFLINE = 'SERVER_OFFLINE',
  CONFIG = 'CONFIG',
  SCRAPING = 'SCRAPING',
  ANALYZING = 'ANALYZING',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR'
}